<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260218135618 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE article (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE citoyen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(50) NOT NULL, telephone VARCHAR(50) NOT NULL, nom VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE signalement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, datesignalement TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(50) NOT NULL, citoyen_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F4B5511443787BBA ON signalement (citoyen_id)');
        $this->addSql('ALTER TABLE signalement ADD CONSTRAINT FK_F4B5511443787BBA FOREIGN KEY (citoyen_id) REFERENCES citoyen (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE signalement DROP CONSTRAINT FK_F4B5511443787BBA');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE citoyen');
        $this->addSql('DROP TABLE signalement');
    }
}
